### ISSUE TITLE
Simultaneous temperature conversion from python

### ISSUE THREAD

**Issue by klintbeastwood** [owfs/owfs#31]
ive installed installed OWFS using apt-get install on my raspberry pi, ive got pyownet and python-ow, im trying to write data directly to several DS18B20 sensors, in order to reduce read time, im trying to send every sensor a convertT command ([44h]according to the data sheet) in order to have all the sensors begin the conversion process, and after the required conversion time, i would go back and read the results from every sensor. rather than waiting for every sensor to do the conversion, im trying to get all sensors to convert simultaneously. can anybody point me in the right direction to accomplish this with python?
thanks

**Comment by taliesin** [comment]
I'm not sure if this will help you, but you could use the 'simultaneous' interface for temperatures:
**'uncached/simultaneous/temperature'**
By writing 1 to it, it should start the conversion on all 'temperature devices' simultaneously, then read from the cached version of your sensors, according to https://www.domoticz.com/forum/viewtopic.php?t=9912 this should improve your acquisition time quite dramatically.
Note that this will work only for non-parasitic mode, i.e. your temperature sensors must have a separate power supply!

Currently I have no setup with more than a few sensors, so I can't try ...

**Comment by klintbeastwood** [comment]
Hey thanks for the reply, I've been trying to code this project in Python but it looks like I'll be ditching Python for C. So I'm not sure if I'm just lacking resources, but I have several ds18b20's connected to a raspberry pi, they are powered directly with 5v and not in parasitic mode. There is no 1-wire bus master in the system, the "bus master" as referred to in most 1-wire systems is the w1 kernel for Linux. Do I need to setup some kind of ow server in order to write commands to the sensors? Or can I just include the one wire library at the top of my code and use functions included in the library to write directly to the sensors?

Thanks for your help, I'm quite new to the world of Linux, sensors and coding,

--
Sent from Mail.Ru app for Android

Saturday, 26 January 2019, 07:34AM -05:00 from taliesin notifications@github.com<mailto:notifications@github.com>:


I'm not sure if this will help you, but you could use the 'simultaneous' interface for temperatures:
'uncached/simultaneous/temperature'
By writing 1 to it, it should start the conversion on all 'temperature devices' simultaneously, then read from the cached version of your sensors, according to https://www.domoticz.com/forum/viewtopic.php?t=9912 this should improve your acquisition time quite dramatically.
Note that this will work only for non-parasitic mode, i.e. your temperature sensors must have a separate power supply!

Currently I have no setup with more than a few sensors, so I can't try ...

**Comment by taliesin** [comment]
Hi,
   I see ... So you are probably accessing it using the w1 sysfs interface of the driver directly (i.e. /sys/bus/w1/devices), which most certainly does not provide the simultaneous stuff as described above.
I was talking about owserver, so you need to 'sudo apt install owfs' on Raspberry, the server is then accessible via the owserver (socket) interface or the mounted fuse file system (depending on configuration but often under /mnt/1wire).

As you were writing to the owfs issue list I assumed you already had owfs installed.

For a pyhton binding you have several options, python-ow (python2 only), trio_owfs (python3 asyncio supported) and some more see https://github.com/owfs/owfs/pull/26 for a discussion.

I just checked https://www.kernel.org/doc/Documentation/w1/slaves/w1_therm and it says that triggering a conversion is not supported.

**Comment by ianka** [comment]
1. Trigger the simultaneous conversion by writing 1 to _/simultaneous/temperature._
2. Wait a second.
3. Read each sensors /uncached/<id>/_latesttemp_ node

Reading the cached value will trigger another conversion, as the cache only tracks values previously read from the very same node. The uncached _latesttemp_ node in contrary reads the value from the sensor without triggering another conversion.

**Comment by miccoli** [comment]
Closing since there was no more input from the OP.

**Comment by klintbeastwood** [comment]
Thanks Stefano, ive been away for a while, not sure if this message will go through since the thread is closed, I very much appreciate your help. I will attempt the steps you have provided

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by miccoli** [comment]
No problem: I will read your messages here. If necessary I will reopen.
