### ISSUE TITLE
Strange DS2482 implementation

### ISSUE THREAD

**Issue by INgoRah** [owfs/owfs#37]
While trying to get an emulation device working with owfs and the ds2482 protocol I was struggling to find out why it this implementation working. The data from the OW bus is never read using the specified command "DS2482_CMD_1WIRE_READ_BYTE " (defined but not even used), but somehow using the datapointer and writing 0xff.
The implementation always reads back the written bytes and also writes (0xff) first if the OW shall be read.
This seems to be a lot of overhead on the I2C bus always setting the read pointer and reading back each byte even if just the data shall be written.

If haven't found any hint in the datasheet, that this even even working with the DS2482. Only the read command 0x96 is reading data from the bus.
Can anyone feedback? 
The code says it was "stolen" from the kernel module, but this (at least now -5 years later) looks different and compliant to the datasheet.

**Comment by ianka** [comment]
As nobody feels compentent to answer this question for almost ten months, I close this issue.

Sorry.
